name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your Render bot
        run: curl -s https://bachatareminder-vio5.onrender.com
